# Generated by Django 4.0.4 on 2022-05-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='clock_active',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
    ]
