# Generated by Django 4.0.4 on 2022-05-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0002_myuser_clock_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='clock',
            name='totalHours',
            field=models.IntegerField(blank=True, default=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clock',
            name='clockIn',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='clock',
            name='clockOut',
            field=models.TimeField(blank=True),
        ),
    ]
