# Generated by Django 4.0.4 on 2022-05-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0003_clock_totalhours_alter_clock_clockin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clock',
            name='clockIn',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clock',
            name='clockOut',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clock',
            name='totalHours',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
