# Generated by Django 4.0.4 on 2022-05-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0004_alter_clock_clockin_alter_clock_clockout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clock',
            name='totalHours',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
