# Generated by Django 4.0.4 on 2022-05-27 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0005_alter_clock_totalhours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='clock_active',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
