# Generated by Django 4.0.4 on 2022-05-27 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0006_alter_myuser_clock_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clock',
            old_name='clockIn',
            new_name='clockedIn',
        ),
        migrations.RenameField(
            model_name='clock',
            old_name='clockOut',
            new_name='clockedOut',
        ),
    ]
